spring.application.name=corp-financial-api
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntax-highlight.theme=tomorrow-night
